---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: nginx
spec:
  releaseName: nginx-ingress
  chart:
    spec:
      chart: nginx-ingress
      # version: "1.37.0"
      sourceRef:
        kind: HelmRepository
        name: nginx
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: nginx
spec:
  interval: 1m
  url: https://helm.nginx.com/stable
